mock_tweets = {
  "took": 11,
  "timed_out": False,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2236,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "tweet_id",
        "_id": "MV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282234625021153280",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @JeshikaLyra: FUN TODAY 😊😊😊 mood on https://t.co/cwatihPql9",
          "tweet_time": "2020-07-12 08:45",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2811923772777923e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1255650154021113862']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Ml7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283068643828314114",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @cuttykitten6136: Brazzers - ★🤪🤪🤪🤪🤩🤩🤩🤩🤩🇱🇷🇱🇷🇱🇷🇱🇷🎀🎀 https://t.co/beC2BNmyrn",
          "tweet_time": "2020-07-14 15:59",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2830652406582886e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1007883309462851584']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "M17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283433010474475520",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": """RT @cuttykitten6136: Bratty Sis "🎀🎀🎀🎀💯🎀🤪🤪🤪🤪🤪🤪🤩🤩🤩 https://t.co/HLm7HJ8H6j""",
          "tweet_time": "2020-07-15 16:07",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2833778243639828e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1007883309462851584']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "NF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283641125081735168",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @cuttykitten6136: He keeps Fucking Creampied Pussy of his Step Sis to Cum again - Eva🎀🎀🎀🎀 Elfie https://t.co/BhzopgUrIg",
          "tweet_time": "2020-07-16 05:54",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.283630144687444e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1007883309462851584']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "NV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1281818978113908736",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @JeshikaLyra: Funny sex https://t.co/gMn40L2fgm",
          "tweet_time": "2020-07-11 05:13",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.281193052690735e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1255650154021113862']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Nl7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282228514209427457",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @cuttykitten6136: 🔝⭐🔝🤩🤩🤩🤩🤪🤪🤪🤪🤪 https://t.co/nHUxIwa3RY",
          "tweet_time": "2020-07-12 08:21",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2819643538273485e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1007883309462851584']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "N17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1277846447916871692",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @ItsLustLife: Hot girl sex  https://t.co/Bm3JmwslW5",
          "tweet_time": "2020-06-30 06:08",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.277809859144999e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1267735037904109570']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "OF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1281824915419611137",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": """RT @joshifucked: Part 👉 2
Plumber girl fucked by the men.
Follow and R
 https://t.co/CXfxpxCon1""",
          "tweet_time": "2020-07-11 05:37",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2817614794698793e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1271268456424325130']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "OV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283195643448528896",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @Erotismo20: You want more than Follow Me https://t.co/eeaTZuVguu",
          "tweet_time": "2020-07-15 00:24",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.282328853357015e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1267809073208033287']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Ol7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282845403889598465",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @joshifucked: So Hard 🔥 https://t.co/mQ0erKwcpw",
          "tweet_time": "2020-07-14 01:12",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2828225688277443e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1271268456424325130']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "O17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283437517023219712",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @seren_izgi: https://t.co/j3ESse0d5L",
          "tweet_time": "2020-07-15 16:25",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2831995359682232e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1262251460357734400']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "PF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283437499927261190",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @seren_izgi: Mood https://t.co/r4f70XXH4v",
          "tweet_time": "2020-07-15 16:25",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2833572356497695e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1262251460357734400']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "PV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283195637144580096",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "in",
          "tweet_text": "RT @Erotismo20: Rt*Rt https://t.co/RQxGeu5n9R",
          "tweet_time": "2020-07-15 00:24",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.283050637694034e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1267809073208033287']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Pl7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283071240253521922",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": """RT @Jee__vikash74: RT 🔄 RT 💦💦💦♥️♥️🔞🔞
Follow 👉 @Jee__vikash74
 https://t.co/bxbUf76wFd""",
          "tweet_time": "2020-07-14 16:09",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2828558915495567e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1270815381079207936', '1270815381079207936']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "P17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282343727743111171",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @Jee__vikash74: https://t.co/0Yjqkw5t0v",
          "tweet_time": "2020-07-12 15:59",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.281995924126851e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1270815381079207936']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "QF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282845697184681986",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @dark0asia: https://t.co/UMkjQTsB8Z",
          "tweet_time": "2020-07-14 01:13",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2827798368181944e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1281621722895011840']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "QV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282845705241939968",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @dark0asia: https://t.co/fiU18UQlJg",
          "tweet_time": "2020-07-14 01:13",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2827517241097544e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1281621722895011840']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Ql7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1279447839173513217",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": """RT @natashalaikk: 🚨My OnlyFans hoy a solo $5😈🤯😱🍑🍆💦🤤
👉 https://t.co/Xp78ege7GV 👈

🚨My OnlyFans SALE $5😱😈🍑💦🤤
👉 https://t.co/Xp78ege7GV 👈 http…""",
          "tweet_time": "2020-07-04 16:11",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2791196852047872e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "['https://onlyfans.com/natashalaikk', 'https://onlyfans.com/natashalaikk']",
          "user_mentions": "['1058714251852955649']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Q17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1278531678915289089",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @love_6202: ❌❌❌❌🔞🔞🔞🔞🔞☑️☑️❌❌🔵🔵🔵https://t.co/pJ1cp807Ip",
          "tweet_time": "2020-07-02 03:31",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2783429963672494e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1000297069813288960']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "RF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282723628463779840",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @Pornstar218: Rt for rt https://t.co/AFgwCmdNWQ",
          "tweet_time": "2020-07-13 17:08",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.282417114054144e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1270191642113277954']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "RV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1278740215364849666",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @love_6202: Rt for Rt 🔵🔵🔵🔵🔵🔵☑️☑️☑️☑️https://t.co/pFBAgzTg4F",
          "tweet_time": "2020-07-02 17:19",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2786103093771674e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1000297069813288960']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Rl7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1281669696857632768",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @Pornstar218: Dancers nice https://t.co/N8vm8LZqrD",
          "tweet_time": "2020-07-10 19:20",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2816652591413576e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1270191642113277954']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "R17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1281439104282972162",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": """RT @Pornstar218: 🕳🕳🖤🖤💭💭🕳🕳🕳🕳💭💭💭😗👄😉😗😇😗😇😗😇😗😇😇😗😇

https://t.co/8VLC5Lkhmt""",
          "tweet_time": "2020-07-10 04:04",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2813111558650511e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1270191642113277954']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "SF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1316632140121997312",
          "userid": "1293391526505009156",
          "user_display_name": "Pink Marsh Pure",
          "user_screen_name": "marsh_pure",
          "user_reported_location": "Tikari, India",
          "user_profile_description": "follow me🌹🌹",
          "user_profile_url": "",
          "follower_count": "6179",
          "following_count": "6773",
          "account_creation_date": "2020-08-12",
          "account_language": "en",
          "tweet_language": "hi",
          "tweet_text": """RT @dranjalidalal: किसान को MSP मिलता ही नही है तो निर्धारित क्यो किया जाता है ये तो धोखा है

              MSP       मंडी का भाव
गे…""",
          "tweet_time": "2020-10-15 06:48",
          "tweet_client_name": "Twitter Web App",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.314735323536978e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['2970880298']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "SV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1282703207362248705",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": """RT @Armen_Arkina: Grow your Dick size Automatically in an efficient, safe &amp; painless way.
Such a very Nice product guy,s👌👍
Buy and enjoy 😘😘…""",
          "tweet_time": "2020-07-13 15:47",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2826102824271094e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1257638839482494976']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Sl7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1274494999510450176",
          "userid": "3480015072",
          "user_display_name": "昶宇文化",
          "user_screen_name": "seo_yea_ji",
          "user_reported_location": "",
          "user_profile_description": """一群有理想的年轻人聚在一起，以视频反映生活，记录生活。
A group of young men with dreams come together to video life and record what we've seen.""",
          "user_profile_url": "",
          "follower_count": "5379",
          "following_count": "361",
          "account_creation_date": "2015-09-07",
          "account_language": "zh-cn",
          "tweet_language": "in",
          "tweet_text": """RT @infodrakor_id: Rating drama Sabtu 200620:

KBS #OnceAgain: 23.1% | 28.8%
SBS #BackstreetRookie: 3.7% | 6.8%

tvN #ItsOkayToNotBeOkay: 6…""",
          "tweet_time": "2020-06-21 00:11",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2744923138556846e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "['OnceAgain', 'BackstreetRookie', 'ItsOkayToNotBeOkay']",
          "urls": "[]",
          "user_mentions": "['1376348437']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "S17P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1281866145524375553",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @Kareena30296936: Nice hot fuking chhut,,, https://t.co/Uipjw1gakQ",
          "tweet_time": "2020-07-11 08:21",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2818607158720553e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1277239749153964032']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "TF7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1289227411519868930",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": """RT @Madison79vc: This guy is clearly as dumb as he sounds 🤣
https://t.co/aKz8D5H9vc""",
          "tweet_time": "2020-07-31 15:52",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "1.2888888761031107e+18",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2889210425602253e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "['https://twitter.com/trentowesrent/status/1288888876103110656']",
          "user_mentions": "['45809254']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "TV7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1283069205533753347",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "en",
          "tweet_text": "RT @Kareena30296936: Dehati hot girl fuking chhut,, https://t.co/aqRrSXwyOx",
          "tweet_time": "2020-07-14 16:01",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2828627648353034e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1277239749153964032']"
        }
      },
      {
        "_index": "tweet_id",
        "_id": "Tl7P3pQByp3SJ-deVoVf",
        "_score": 1,
        "_source": {
          "tweetid": "1280167927094767616",
          "userid": "1267468640586043392",
          "user_display_name": "★᭄ꦿ᭄ꦿE̺͆R̺͆I̺͆C̺͆A̺͆A̺͆S̺͆E̺͆N̺͆N̺͆★᭄ꦿ᭄ꦿ",
          "user_screen_name": "ericaasenn",
          "user_reported_location": "",
          "user_profile_description": "promat karana hai to DM me",
          "user_profile_url": "",
          "follower_count": "58602",
          "following_count": "1",
          "account_creation_date": "2020-06-01",
          "account_language": "en",
          "tweet_language": "und",
          "tweet_text": "RT @KycTrai: https://t.co/ZXlDO7fKBB",
          "tweet_time": "2020-07-06 15:53",
          "tweet_client_name": "Twitter for Android",
          "in_reply_to_userid": "",
          "in_reply_to_tweetid": "",
          "quoted_tweet_tweetid": "",
          "is_retweet": "True",
          "retweet_userid": "",
          "retweet_tweetid": "1.2801541780026286e+18",
          "latitude": "absent",
          "longitude": "absent",
          "quote_count": "0",
          "reply_count": "0",
          "like_count": "0",
          "retweet_count": "0",
          "hashtags": "[]",
          "urls": "[]",
          "user_mentions": "['1277238372965048326']"
        }
      }
    ]
  },
  "aggregations": {
    "top_users": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 4,
      "buckets": [
        {
          "key": "ericaasenn",
          "doc_count": 990
        },
        {
          "key": "seo_yea_ji",
          "doc_count": 668
        },
        {
          "key": "visualsgallery",
          "doc_count": 216
        },
        {
          "key": "minboxradio",
          "doc_count": 119
        },
        {
          "key": "chaoticeveel",
          "doc_count": 84
        },
        {
          "key": "naturephoto17",
          "doc_count": 58
        },
        {
          "key": "quitebabu",
          "doc_count": 45
        },
        {
          "key": "marsh_pure",
          "doc_count": 25
        },
        {
          "key": "dishapa65190266",
          "doc_count": 19
        },
        {
          "key": "loveflowers_0",
          "doc_count": 8
        }
      ]
    },
    "top_hashtags": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 111,
      "buckets": [
        {
          "key": "사이코지만괜찮아",
          "doc_count": 80
        },
        {
          "key": "tvn",
          "doc_count": 71
        },
        {
          "key": "서예지",
          "doc_count": 71
        },
        {
          "key": "김수현",
          "doc_count": 69
        },
        {
          "key": "토일드라마",
          "doc_count": 68
        },
        {
          "key": "박규영",
          "doc_count": 67
        },
        {
          "key": "오정세",
          "doc_count": 67
        },
        {
          "key": "itsokaytonotbeokay",
          "doc_count": 45
        },
        {
          "key": "seoyeji",
          "doc_count": 33
        },
        {
          "key": "kimsoohyun",
          "doc_count": 28
        }
      ]
    },
    "top_urls": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 962,
      "buckets": [
        {
          "key": "https",
          "doc_count": 182
        },
        {
          "key": "watch",
          "doc_count": 97
        },
        {
          "key": "v",
          "doc_count": 94
        },
        {
          "key": "www.youtube.com",
          "doc_count": 94
        },
        {
          "key": "youtu.be",
          "doc_count": 37
        },
        {
          "key": "article",
          "doc_count": 31
        },
        {
          "key": "feature",
          "doc_count": 31
        },
        {
          "key": "status",
          "doc_count": 31
        },
        {
          "key": "twitter.com",
          "doc_count": 31
        },
        {
          "key": "www.soompi.com",
          "doc_count": 29
        }
      ]
    }
  }
}